---
kind: pipeline
type: docker
name: mpn:latest

platform:
  os: linux
  arch: amd64

steps:
- name: pull
  image: omerxx/drone-ecr-auth
  commands:
  - $(aws ecr get-login --no-include-email --region us-east-1)
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.0:latest
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:latest
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock


- name: Install bbi
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:latest
  commands:
  - chmod +x install_bbi.sh
  - ./install_bbi.sh -p /ephemeral/bbi -v 'v3.2.0-alpha.4'
  volumes:
  - name: cache
    path: /ephemeral

- name: "Check package: R 4.0"
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.0:latest
  commands:
  - R -s -e 'devtools::install_deps(upgrade = '"'"'never'"'"')'
  - R -s -e 'devtools::check(env_vars = c("BBI_EXE_PATH" = "/ephemeral/bbi", "NOT_CRAN" = "true"))'
  environment:
    BBI_EXE_PATH: /ephemeral/bbi
    NOT_CRAN: true
  volumes:
  - name: cache
    path: /ephemeral

- name: "Check package: R 4.1"
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:latest
  commands:
  - R -s -e 'devtools::install_deps(upgrade = '"'"'never'"'"')'
  - R -s -e 'devtools::check(env_vars = c("BBI_EXE_PATH" = "/ephemeral/bbi", "NOT_CRAN" = "true"))'
  environment:
    BBI_EXE_PATH: /ephemeral/bbi
  volumes:
  - name: cache
    path: /ephemeral

volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock
- name: cache
  temp: {}

trigger:
  event:
    exclude:
    - promote

---
kind: pipeline
type: docker
name: mpn:oldest

platform:
  os: linux
  arch: amd64

steps:
- name: pull
  image: omerxx/drone-ecr-auth
  commands:
  - $(aws ecr get-login --no-include-email --region us-east-1)
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.0:2020-06-08
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock

- name: Install bbi
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.0:2020-06-08
  commands:
  - chmod +x install_bbi.sh
  - ./install_bbi.sh -p /ephemeral/bbi -v 'v3.2.0-alpha.4'
  volumes:
  - name: cache
    path: /ephemeral

- name: "Check package: R 4.0"
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.0:2020-06-08
  commands:
  - R -s -e 'devtools::install_deps(upgrade = '"'"'never'"'"')'
  - R -s -e 'devtools::check(env_vars = c("BBI_EXE_PATH" = "/ephemeral/bbi", "NOT_CRAN" = "true"))'
  environment:
    BBI_EXE_PATH: /ephemeral/bbi
    NOT_CRAN: true
  volumes:
  - name: cache
    path: /ephemeral

volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock
- name: cache
  temp: {}

trigger:
  event:
    exclude:
    - promote

---
kind: pipeline
type: docker
name: cran-latest

platform:
  os: linux
  arch: amd64

steps:
- name: pull
  image: omerxx/drone-ecr-auth
  commands:
  - $(aws ecr get-login --no-include-email --region us-east-1)
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.0:cran-latest
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:cran-latest
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock

- name: Install bbi
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:cran-latest
  commands:
  - chmod +x install_bbi.sh
  - ./install_bbi.sh -p /ephemeral/bbi -v 'v3.2.0-alpha.4'
  volumes:
  - name: cache
    path: /ephemeral

- name: "Check package: R 4.0"
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.0:cran-latest
  commands:
  - R -s -e 'devtools::install_deps(upgrade = '"'"'always'"'"')'
  - R -s -e 'devtools::load_all(); sessioninfo::session_info()'
  - R -s -e 'devtools::check(env_vars = c("BBI_EXE_PATH" = "/ephemeral/bbi", "NOT_CRAN" = "true"))'
  environment:
    BBI_EXE_PATH: /ephemeral/bbi
    NOT_CRAN: true
  volumes:
  - name: cache
    path: /ephemeral


- name: "Check package: R 4.1"
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:cran-latest
  commands:
  - R -s -e 'devtools::install_deps(upgrade = '"'"'always'"'"')'
  - R -s -e 'devtools::load_all(); sessioninfo::session_info()'
  - R -s -e 'devtools::check(env_vars = c("BBI_EXE_PATH" = "/ephemeral/bbi", "NOT_CRAN" = "true"))'
  environment:
    BBI_EXE_PATH: /ephemeral/bbi
    NOT_CRAN: true
  volumes:
  - name: cache
    path: /ephemeral

volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock
- name: cache
  temp: {}

trigger:
  event:
    exclude:
    - promote

---
kind: pipeline
type: docker
name: bbr-coverage

platform:
  os: linux
  arch: amd64

steps:
- name: pull
  image: omerxx/drone-ecr-auth
  commands:
  - $(aws ecr get-login --no-include-email --region us-east-1)
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:latest
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock

- name: Install bbi
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:latest
  commands:
  - chmod +x install_bbi.sh
  - ./install_bbi.sh -p /ephemeral/bbi -v 'v3.2.0-alpha.4'
  volumes:
  - name: cache
    path: /ephemeral

- name: Code coverage
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:latest
  commands:
  - R -s -e 'devtools::install_deps(upgrade = '"'"'never'"'"')'
  - R -s -e 'covr::codecov()'
  environment:
    BBI_EXE_PATH: /ephemeral/bbi
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN
    NOT_CRAN: true
  volumes:
  - name: cache
    path: /ephemeral

volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock
- name: cache
  temp: {}

trigger:
  event:
    exclude:
    - promote

depends_on:
- mpn:latest
- cran-latest
---
kind: pipeline
type: docker
name: bbr-release

platform:
  os: linux
  arch: amd64

steps:
- name: pull
  image: omerxx/drone-ecr-auth
  commands:
  - $(aws ecr get-login --no-include-email --region us-east-1)
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:latest
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock

- name: Install bbi
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:latest
  commands:
  - chmod +x install_bbi.sh
  - ./install_bbi.sh -p /ephemeral/bbi -v 'v3.2.0-alpha.4'
  volumes:
  - name: cache
    path: /ephemeral

- name: Build package
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-mpn-4.1:latest
  commands:
  - git config --global user.email drone@metrumrg.com
  - git config --global user.name Drony
  - git fetch --tags
  - R -s -e 'pkgpub::create_tagged_repo(.dir = '"'"'/ephemeral'"'"')'
  environment:
    BBI_EXE_PATH: /ephemeral/bbi
    NOT_CRAN: true
  volumes:
  - name: cache
    path: /ephemeral

- name: "Publish package: ${DRONE_TAG}"
  pull: if-not-exists
  image: plugins/s3
  settings:
    bucket: mpn.metworx.dev
    source: /ephemeral/${DRONE_TAG}/**/*
    strip_prefix: /ephemeral/${DRONE_TAG}/
    target: /releases/${DRONE_REPO_NAME}/${DRONE_TAG}
  volumes:
  - name: cache
    path: /ephemeral

- name: "Publish package: latest_tag"
  pull: if-not-exists
  image: plugins/s3
  settings:
    bucket: mpn.metworx.dev
    source: /ephemeral/${DRONE_TAG}/**/*
    strip_prefix: /ephemeral/${DRONE_TAG}/
    target: /releases/${DRONE_REPO_NAME}/latest_tag
  volumes:
  - name: cache
    path: /ephemeral

volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock
- name: cache
  temp: {}

trigger:
  event:
  - tag

depends_on:
- mpn:latest
- mpn:oldest
- cran-latest
