---
kind: pipeline
type: docker
name: bbr-mpn-dev:latest

platform:
  os: linux
  arch: amd64

steps:
- name: Pull image
  image: omerxx/drone-ecr-auth
  commands:
  - $(aws ecr get-login --no-include-email --region us-east-1)
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn-dev:latest
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock

- name: Install bbi
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn-dev:latest
  commands:
  - wget -O bbi.tar.gz -q https://github.com/metrumresearchgroup/bbi/releases/download/v3.0.0/bbi_linux_amd64.tar.gz
  - tar -xzf bbi.tar.gz
  - rm bbi.tar.gz
  - chmod +x bbi_linux_amd64/bbi
  - mv bbi_linux_amd64/bbi /ephemeral
  volumes:
  - name: cache
    path: /ephemeral

- name: "Check package: R 4.0"
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn-dev:latest
  commands:
  - export PATH=/ephemeral:$PATH
  - . /etc/environment
  - $${R_EXE_4_0} -e 'devtools::install_deps(upgrade = '"'"'never'"'"')'
  - $${R_EXE_4_0} -e 'devtools::check(env_vars = c("BBI_EXE_PATH" = "/ephemeral/bbi", "NOT_CRAN" = "true"))'
  environment:
    BBI_EXE_PATH: /ephemeral/bbi
    NOT_CRAN: true
    R_LIBS_USER: /opt/rpkgs/4.0
  volumes:
  - name: cache
    path: /ephemeral

- name: "Check package: R 3.6"
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn-dev:latest
  commands:
  - export PATH=/ephemeral:$PATH
  - . /etc/environment
  - $${R_EXE_3_6} -e 'devtools::install_deps(upgrade = '"'"'never'"'"')'
  - $${R_EXE_3_6} -e 'devtools::check(env_vars = c("BBI_EXE_PATH" = "/ephemeral/bbi", "NOT_CRAN" = "true"))'
  environment:
    BBI_EXE_PATH: /ephemeral/bbi
    NOT_CRAN: true
    R_LIBS_USER: /opt/rpkgs/3.6
  volumes:
  - name: cache
    path: /ephemeral

volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock
- name: cache
  temp: {}

trigger:
  event:
    exclude:
    - promote

---
kind: pipeline
type: docker
name: bbr-mpn-dev:2020-03-24

platform:
  os: linux
  arch: amd64

steps:
- name: Pull image
  image: omerxx/drone-ecr-auth
  commands:
  - $(aws ecr get-login --no-include-email --region us-east-1)
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn-dev:2020-03-24
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock

- name: Install bbi
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn-dev:2020-03-24
  commands:
  - wget -O bbi.tar.gz -q https://github.com/metrumresearchgroup/bbi/releases/download/v3.0.0/bbi_linux_amd64.tar.gz
  - tar -xzf bbi.tar.gz
  - rm bbi.tar.gz
  - chmod +x bbi_linux_amd64/bbi
  - mv bbi_linux_amd64/bbi /ephemeral
  volumes:
  - name: cache
    path: /ephemeral

- name: "Check package: R 4.0"
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn-dev:2020-03-24
  commands:
  - export PATH=/ephemeral:$PATH
  - . /etc/environment
  - $${R_EXE_4_0} -e 'devtools::install_deps(upgrade = '"'"'never'"'"')'
  - $${R_EXE_4_0} -e 'devtools::check(env_vars = c("BBI_EXE_PATH" = "/ephemeral/bbi", "NOT_CRAN" = "true"))'
  environment:
    BBI_EXE_PATH: /ephemeral/bbi
    NOT_CRAN: true
    R_LIBS_USER: /opt/rpkgs/4.0
  volumes:
  - name: cache
    path: /ephemeral

- name: "Check package: R 3.6"
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn-dev:2020-03-24
  commands:
  - export PATH=/ephemeral:$PATH
  - . /etc/environment
  - $${R_EXE_3_6} -e 'devtools::install_deps(upgrade = '"'"'never'"'"')'
  - $${R_EXE_3_6} -e 'devtools::check(env_vars = c("BBI_EXE_PATH" = "/ephemeral/bbi", "NOT_CRAN" = "true"))'
  environment:
    BBI_EXE_PATH: /ephemeral/bbi
    NOT_CRAN: true
    R_LIBS_USER: /opt/rpkgs/3.6
  volumes:
  - name: cache
    path: /ephemeral

volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock
- name: cache
  temp: {}

trigger:
  event:
    exclude:
    - promote
---
kind: pipeline
type: docker
name: cran-latest:4.0.3

platform:
  os: linux
  arch: amd64

steps:
- name: pull
  image: omerxx/drone-ecr-auth
  commands:
  - $(aws ecr get-login --no-include-email --region us-east-1)
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-cran-latest:4.0.3
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock

- name: Install bbi
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-cran-latest:4.0.3
  commands:
  - wget -O bbi.tar.gz -q https://github.com/metrumresearchgroup/bbi/releases/download/v3.0.0/bbi_linux_amd64.tar.gz
  - tar -xzf bbi.tar.gz
  - rm bbi.tar.gz
  - chmod +x bbi_linux_amd64/bbi
  - mv bbi_linux_amd64/bbi /ephemeral
  volumes:
  - name: cache
    path: /ephemeral
  depends_on:
  - pull

- name: "Check package: R 4.0"
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-cran-latest:4.0.3
  commands:
  - export PATH=/ephemeral:$PATH
  - . /etc/environment
  - R -s -e 'devtools::install_deps(upgrade = '"'"'always'"'"')'
  - R -s -e 'devtools::load_all(); sessioninfo::session_info()'
  - R -s -e 'devtools::check(env_vars = c("BBI_EXE_PATH" = "/ephemeral/bbi", "NOT_CRAN" = "true"))'
  environment:
    BBI_EXE_PATH: /ephemeral/bbi
    NOT_CRAN: true
  volumes:
  - name: cache
    path: /ephemeral
  depends_on:
  - Install bbi

volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock
- name: cache
  temp: {}

trigger:
  event:
    exclude:
    - promote

---
kind: pipeline
type: docker
name: cran-latest:3.6.3

platform:
  os: linux
  arch: amd64

steps:
- name: Pull image
  image: omerxx/drone-ecr-auth
  commands:
  - $(aws ecr get-login --no-include-email --region us-east-1)
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-ci-dev-cran-latest:3.6.3
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock

- name: Install bbi
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/cran-latest:latest
  commands:
  - wget -O bbi.tar.gz -q https://github.com/metrumresearchgroup/bbi/releases/download/v3.0.0/bbi_linux_amd64.tar.gz
  - tar -xzf bbi.tar.gz
  - rm bbi.tar.gz
  - chmod +x bbi_linux_amd64/bbi
  - mv bbi_linux_amd64/bbi /ephemeral
  volumes:
  - name: cache
    path: /ephemeral

- name: "Check package: R 3.6"
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/cran-latest:latest
  commands:
  - export PATH=/ephemeral:$PATH
  - . /etc/environment
  - R -e 'devtools::install_deps(upgrade = '"'"'never'"'"')'
  - R -s -e 'devtools::load_all(); sessioninfo::session_info()'
  - R -s -e 'devtools::check(env_vars = c("BBI_EXE_PATH" = "/ephemeral/bbi", "NOT_CRAN" = "true"))'
  environment:
    BBI_EXE_PATH: /ephemeral/bbi
    NOT_CRAN: true
  volumes:
  - name: cache
    path: /ephemeral

volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock
- name: cache
  temp: {}

trigger:
  event:
    exclude:
    - promote

---
kind: pipeline
type: docker
name: bbr-coverage

platform:
  os: linux
  arch: amd64

steps:
- name: Pull image
  image: omerxx/drone-ecr-auth
  commands:
  - $(aws ecr get-login --no-include-email --region us-east-1)
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn-dev:latest
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock

- name: Install bbi
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn-dev:latest
  commands:
  - wget -O bbi.tar.gz -q https://github.com/metrumresearchgroup/bbi/releases/download/v3.0.0/bbi_linux_amd64.tar.gz
  - tar -xzf bbi.tar.gz
  - rm bbi.tar.gz
  - chmod +x bbi_linux_amd64/bbi
  - mv bbi_linux_amd64/bbi /ephemeral
  volumes:
  - name: cache
    path: /ephemeral

- name: Code coverage
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/r-dev-ci-cran-latest:4.0.3
  commands:
  - export PATH=/ephemeral:$PATH
  - . /etc/environment
  - $${R_EXE_4_0} -e 'devtools::install_deps(upgrade = '"'"'never'"'"')'
  - $${R_EXE_4_0} -e 'covr::codecov()'
  environment:
    BBI_EXE_PATH: /ephemeral/bbi
    CODECOV_TOKEN:
      from_secret: CODECOV_TOKEN
    NOT_CRAN: true
    R_LIBS_USER: /opt/rpkgs/4.0
  volumes:
  - name: cache
    path: /ephemeral

volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock
- name: cache
  temp: {}

trigger:
  event:
    exclude:
    - promote

---
kind: pipeline
type: docker
name: bbr-release

platform:
  os: linux
  arch: amd64

steps:
- name: Pull image
  image: omerxx/drone-ecr-auth
  commands:
  - $(aws ecr get-login --no-include-email --region us-east-1)
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn-dev:latest
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock

- name: Install bbi
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn-dev:latest
  commands:
  - wget -O bbi.tar.gz -q https://github.com/metrumresearchgroup/bbi/releases/download/v3.0.0/bbi_linux_amd64.tar.gz
  - tar -xzf bbi.tar.gz
  - rm bbi.tar.gz
  - chmod +x bbi_linux_amd64/bbi
  - mv bbi_linux_amd64/bbi /ephemeral
  volumes:
  - name: cache
    path: /ephemeral

- name: Build package
  pull: never
  image: 906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn-dev:latest
  commands:
  - git config --global user.email drone@metrumrg.com
  - git config --global user.name Drony
  - git fetch --tags
  - export PATH=/ephemeral:$PATH
  - . /etc/environment
  - $${R_EXE_4_0} -e 'pkgpub::create_tagged_repo(.dir = '"'"'/ephemeral'"'"')'
  environment:
    BBI_EXE_PATH: /ephemeral/bbi
    NOT_CRAN: true
    R_LIBS_USER: /opt/rpkgs/4.0
  volumes:
  - name: cache
    path: /ephemeral

- name: "Publish package: ${DRONE_TAG}"
  pull: if-not-exists
  image: plugins/s3
  settings:
    bucket: mpn.metworx.dev
    source: /ephemeral/${DRONE_TAG}/**/*
    strip_prefix: /ephemeral/${DRONE_TAG}/
    target: /releases/${DRONE_REPO_NAME}/${DRONE_TAG}
  volumes:
  - name: cache
    path: /ephemeral

- name: "Publish package: latest_tag"
  pull: if-not-exists
  image: plugins/s3
  settings:
    bucket: mpn.metworx.dev
    source: /ephemeral/${DRONE_TAG}/**/*
    strip_prefix: /ephemeral/${DRONE_TAG}/
    target: /releases/${DRONE_REPO_NAME}/latest_tag
  volumes:
  - name: cache
    path: /ephemeral

volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock
- name: cache
  temp: {}

trigger:
  event:
  - tag

depends_on:
- bbr-mpn-dev:latest
- bbr-mpn-dev:2020-03-24
- bbr-cran-latest:latest
