kind: pipeline
type: docker
name: rbabylon

#Gobal variable definitions and anchors
global-variables:
    environment: &default_environment
        BABYLON_URL: https://www.github.com/metrumresearchgroup/babylon/releases/latest/download/bbi_linux_amd64.tar.gz
        BABYLON_VERSION: 2.1.1-rc1 # Not currently used

steps:
- name: Pull mpn container from ECR
  image: omerxx/drone-ecr-auth
  volumes:
  - name: docker.sock
    path: /var/run/docker.sock
  commands:
  - $(aws ecr get-login --no-include-email --region us-east-1)
  - docker pull 906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn:2020-05-09

- name: R36
  image: "906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn:2020-05-09"
  pull: never
  environment:
    R_LIBS_USER: "/opt/rpkgs/3.6/2020-05-09"
    # Reading in entire anchor
    <<: *default_environment
  commands:
  # download and setup bbi
  - wget $BABYLON_URL -O bbi.tar.gz
  - tar -xzf bbi.tar.gz
  - rm bbi.tar.gz
  - chmod +x bbi_linux_amd64/bbi
  - mkdir -p /data/apps
  - mv bbi_linux_amd64/bbi /data/apps
  - ls -la /data/apps
  - /data/apps/bbi -h
  - export PATH=/data/apps:$PATH
  - /opt/R/3.6.2/bin/R -e "devtools::install_deps(upgrade = 'never')"
  - /opt/R/3.6.2/bin/R -e "devtools::test()"
  - /opt/R/3.6.2/bin/R -e "devtools::check()"


- name: R35
  image: "906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn:2020-05-09"
  pull: never
  environment:
    R_LIBS_USER: "/opt/rpkgs/3.5/2020-05-09"
    <<: *default_environment
  commands:
  # download and setup bbi
  - wget $BABYLON_URL -O bbi.tar.gz
  - tar -xzf bbi.tar.gz
  - rm bbi.tar.gz
  - ls -la bbi_linux_amd64
  - chmod +x bbi_linux_amd64/bbi
  - mkdir -p /data/apps
  - mv bbi_linux_amd64/bbi /data/apps
  - export PATH=/data/apps:$PATH
  - /opt/R/3.5.3/bin/R -e "devtools::install_deps(upgrade = 'never')"
  - /opt/R/3.5.3/bin/R -e "devtools::test()"
  - /opt/R/3.5.3/bin/R -e "devtools::check()"

- name: release
  when:
    event:
    - tag
    status:
    - success
  image: "906087756158.dkr.ecr.us-east-1.amazonaws.com/mpn:2020-05-09"
  pull: never
  environment:
    R_LIBS_USER: "/opt/rpkgs/3.6/2020-05-09"
    <<: *default_environment
  commands:
  # download and setup bbi
  - wget $BABYLON_URL -O bbi.tar.gz
  - tar -xzf bbi.tar.gz
  - rm bbi.tar.gz
  - chmod +x bbi_linux_amd64/bbi
  - mkdir -p /data/apps
  - mv bbi_linux_amd64/bbi /data/apps
  - export PATH=/data/apps:$PATH
  - git config --global user.email "drone@metrumrg.com"
  - git config --global user.name "Drony"
  - git fetch --tags
  - R -e "pkgpub::create_tagged_repo()"
  - aws s3 sync /tmp/${DRONE_TAG} s3://mpn.metworx.dev/releases/${DRONE_REPO_NAME}/${DRONE_TAG}
  - aws s3 sync /tmp/${DRONE_TAG} s3://mpn.metworx.dev/releases/${DRONE_REPO_NAME}/latest_tag

volumes:
- name: docker.sock
  host:
    path: /var/run/docker.sock
