---
title: "Untitled"
output: html_document
---


```{r}
library(rbabylon)
```

# execution

```{r}
bbi_init("nonmem", "/opt/NONMEM")
```

```{r}
res <- submit_nonmem_model("nonmem/acop.mod", .type = "local", .args = list(overwrite = TRUE))
```
## misspecifying params should error out with the problematic error

```{r eval=FALSE}
#res <- submit_nonmem_model("nonmem/acop.mod", .type = "local", .args = list(overwrite = "bad"))
res <- submit_nonmem_model("nonmem/acop.mod", .type = "local")
```


```{r}
cat(res$stderr)
```

## model summarizations

```{r}
nonmem_output <- function(.x, ...) {
  UseMethod("nonmem_output")
}

nonmem_output.babylon_result <- function(.x, output_dir = NULL) {
  # do something from result object
}

nonmem_output.character <- function(.x, ...) {
  # do something from a string (assumed path)
}

```

```{r}
# in this case originally output dir named acop, but as that is ignored so it can be run
# often 
acop_output <- nonmem_output("nonmem/output_acop/")
acop_output <- nonmem_output(res)
```

```{r}
class(acop_output) <- c("babylon_nonmem")
```

```{r}
class(acop_output)
```

```{r}
.x <- acop_output
param_estimates.babylon_nonmem <- function(.x) {
  num_methods <- length(.x$parameters_data)
  param_names <- .x$parameter_names 
  param_estimates <- .x$parameters_data[[num_methods]]$estimates
  tibble::tibble(
    names = unlist(param_names),
    estimate = unlist(param_estimates),
    stderr = unlist(.x$parameters_data[[num_methods]]$std_err) %||% NA_real_,
    fixed = unlist(.x$parameters_data[[num_methods]]$fixed),
    )
}
```

```{r}
param_estimates(acop_output)
```

```{r}
param_estimates(acop_output)
```

```{r}
theta_cov(acop_output)
```

