name: coverage
on:
  push:
    branches:
      - 'main'
      - 'scratch/**'
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install bbi
        uses: metrumresearchgroup/actions/setup-bbi@v1
        with:
          version: v3.3.0
      - uses: metrumresearchgroup/actions/mpn-latest@v1
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: release
          use-public-rspm: true
          extra-repositories: 'https://mpn.metworx.com/snapshots/stable/${{ env.MPN_LATEST }}'
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          upgrade: 'TRUE'
      - name: Run covr
        shell: Rscript {0}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: covr::codecov()
